# Registro nube de puntos

In [1]:
import cv2
import numpy as np
import open3d as o3d
import copy
from scipy.spatial.distance import directed_hausdorff

Leer datos y asignarle un color uniforme

In [2]:
pcd = o3d.io.read_point_cloud('dragon_fijo.ply')
pcd2 = o3d.io.read_point_cloud('dragon_des.ply')

pcd.paint_uniform_color([1, 0.5, 0])
pcd2.paint_uniform_color([0, 0.651, 0.929])

PointCloud with 100250 points.

Matriz de transformacion inicial y threshold

In [3]:
threshold = 0.009
trans_matrix = np.asarray([[1.0, 0.0, 0.0, 0.],
                             [0.0, 1.0, 0.0, 0.0],
                             [0.0, 0.0, 1.0, 0.0], 
                             [0.0, 0.0, 0.0, 1.0]])

Aplicar funcion de ICP, imprimir matriz de transformacion resultante

In [4]:
reg_p2p = o3d.pipelines.registration.registration_icp(pcd2, pcd, threshold, trans_matrix,o3d.pipelines.registration.TransformationEstimationPointToPoint())
print(reg_p2p)
print("Matriz de transformacion:")
print(reg_p2p.transformation)
print("")

Apply point-to-point ICP
RegistrationResult with fitness=1.000000e+00, inlier_rmse=1.164588e-03, and correspondence_set size of 100250
Access transformation to get result.
Transformation is:
[[ 9.82626509e-01  1.85094433e-01  1.36086113e-02  1.29275536e-03]
 [-1.84998976e-01  9.82706328e-01 -7.97826514e-03 -1.63432211e-04]
 [-1.48500009e-02  5.32207567e-03  9.99875569e-01 -6.95582978e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]



Transformar nube de puntos desplazada

In [5]:
pcd2.transform(reg_p2p.transformation)

PointCloud with 100250 points.

Calcular distancia de Hausdorff con funcion

In [6]:
haus=directed_hausdorff(pcd2.points, pcd.points)
print('Distancia Hausdorf: ', haus[0])

Distancia Hausdorf:  0.004242925161647568


Desplegar las dos nubes de puntos

In [7]:
o3d.visualization.draw_geometries([pcd, pcd2])